// @ts-check

const path = require('path');

const remarkGfmAlerts = require('./src/plugins/remark-gfm-alerts');
const remarkExternalUrl = require('./src/plugins/remark-external-url');
const remarkFileItem = require('./src/plugins/remark-file-item');
const remarkReferenceItem = require('./src/plugins/remark-reference-item');
const remarkHtmlLinks = require('./src/plugins/remark-html-links');
const { loadCourseConfig } = require('./lib/config/course-config');
const { loadTheme } = require('./lib/config/theme');

// The course title names the site and its navbar. Course language drives the
// site locale (Docusaurus theme chrome ships translations) and every label the
// remark plugins render. All of it comes from course.config.yml, which upstream
// updates never overwrite — unlike this file.
const { title, tagline, language, labels } = loadCourseConfig(__dirname);

// The selected theme declares the --cw-* colour and font tokens that
// custom.css maps onto Infima's variables, so it has to load first.
const themeCss =
  './' +
  path.relative(__dirname, loadTheme(__dirname).file).split(path.sep).join('/');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title,
  tagline,
  favicon: 'img/favicon.ico',

  // The deploy workflow passes the site's public address in from GitHub Pages,
  // which knows it for whatever repository the build runs in, so nothing has to
  // be written into this file per course. A local build keeps the placeholders;
  // they only surface in absolute URLs such as the sitemap's.
  url: process.env.CW_SITE_URL || 'https://example.com',
  baseUrl: process.env.CW_BASE_URL || '/',

  onBrokenLinks: 'throw',

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  i18n: {
    defaultLocale: language,
    locales: [language],
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'course',
          routeBasePath: '/',
          sidebarPath: undefined, // autogenerated sidebar
          beforeDefaultRemarkPlugins: [
            [remarkGfmAlerts, { titles: labels.alerts }],
            [remarkExternalUrl, { label: labels.cards.external_url }],
            [remarkFileItem, { siteDir: __dirname, label: labels.cards.file }],
            [
              remarkReferenceItem,
              {
                cards: labels.cards,
                reference: labels.reference,
                projectDir: __dirname,
              },
            ],
            remarkHtmlLinks,
          ],
        },
        blog: false,
        theme: {
          customCss: [themeCss, './src/css/custom.css'],
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      docs: {
        sidebar: {
          hideable: true,
        },
      },
      colorMode: {
        defaultMode: 'light',
        disableSwitch: true,
        respectPrefersColorScheme: false,
      },
      navbar: {
        title,
        items: [],
      },
      footer: {
        style: 'dark',
        copyright: `Copyright © ${new Date().getFullYear()}`,
      },
      prism: {
        theme: require('prism-react-renderer').themes.oneDark,
        additionalLanguages: ['java'],
      },
    }),
};

module.exports = config;
